### ISSUE TITLE
点击“获取订阅链接”没有反应。

### ISSUE THREAD

**Issue by FreeBom** [adproqwq/GKD_sub_share#2]
点击“获取订阅链接”没有反应。
控制台报错如下：
![微信截图_20240704135845](https://github.com/adproqwq/GKD_sub_share/assets/59219170/0bb6f0f8-344b-4a0c-8ece-707f00cae98f)

**Comment by adproqwq** [comment]
请先安装这个[油猴脚本](https://github.com/gkd-kit/network-extension)

**Comment by adproqwq** [comment]
已经加了油猴脚本安装相关内容，未安装油猴脚本时，获取链接会给出提示。
